### PR TITLE
Addresses #19 - Add support for .NET 5.0

### PR DESCRIPTION
**Pull request by hellfirehd**
This implements multi-target (`netstandard2.1` and `net5.0`) and increments to v1.5.0.  I'd rather not do that, instead going with a major version bump and dropping support for `netstandard2.1`.

### CODE REVIEW

**Comment by mrpmorris** [comment]
Thanks for this!

I'll review it fully when Net5 is fully released.

**Comment by mrpmorris** [comment]
Is the only change in Net5 the renaming of a method I invoke via reflection?

**Comment by hellfirehd** [comment]
The only file with a significant code code change is:

`src/PeterLeslieMorris.Blazor.Validation/Extensions/EditContextExtensions.cs`

Additionally, the `.csproj` files have the `net5.0` target framework added.
 From:
`<TargetFramework>netstandard2.1</TargetFramework>`
To:
`<TargetFrameworks>netstandard2.1;net5.0</TargetFrameworks>`

With corresponding conditionals added as required, e.g. `<ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.1' ">`

Also bumped minor version to: 1.5.0

**Comment by hellfirehd** [comment]
Incidentally, I've been developing against this for about a month with no issues so far.  If there's any improvements I can make, please let me know!

**Comment by mrpmorris** [comment]
Is it possible to only make the library target two frameworks and have the IFDEF around the offending code? I'd like to leave the demos at standard 2.1 to minimise the amount of changes.

**Comment by hellfirehd** [comment]
I believe that’s what I did.

**Comment by mrpmorris** [comment]
There are 36 files in the PR

**Comment by hellfirehd** [comment]
Yes, most of which are a new NET5 sample project.

**Comment by mrpmorris** [comment]
Why add Net5 samples?  Standard2.1 demos are enough aren't they?

**Pull request closed without merging**
